M48
; DRILL file {KiCad 7.0.4} date Sun 09 Jul 2023 08:25:26 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-09T20:25:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X5.9055Y-2.122
T2
X5.9055Y-2.2992
T3
X4.1614Y-2.1063
X4.1614Y-4.0039
X7.6496Y-2.1063
X7.6496Y-3.2559
T0
M30
